#include<iostream.h>
#include<conio.h>
void main()
{
 clrscr();
 cout<<"    1    |      4      |      7      |"<<endl;
 cout<<"         |             |             |"<<endl;
 cout<<"______________________________________"<<endl;
 cout<<"         |             |             |"<<endl;
 cout<<"   2     |      5      |      8      |"<<endl;
 cout<<"______________________________________"<<endl;
 cout<<"         |             |             |"<<endl;
 cout<<"   3     |      6      |      9      |"<<endl;
 getch();
}